### ISSUE TITLE
opam-doc off-line

### ISSUE THREAD

**Issue by correnson** [ocamllabs/opam-doc#106]
When I use ocaml-doc offline (on the default localhost:8000) package lists are always empty.
As soon as I retrieve an internet connection, documentation is fully served.

**Comment by lpw25** [comment]
I'm currently working on a complete re-write of opam-doc, so I'm unlikely to address this issue.  Without looking at it properly, I would guess that it is related to the various restrictions that browsers place on local/cross-domain AJAX requests. The new version does not use AJAX requests, so hopefully this will not be a problem. (Sorry for the extremely late reply).
