### ISSUE TITLE
Problem with .opam/doc and .opam/doc/lock

### ISSUE THREAD

**Issue by correnson** [ocamllabs/opam-doc#107]
with: opam 1.2.0 and opam-doc 9.6.3

When $HOME/.opam/doc don't exists:
$ opam doc <some pkg>
Fatal error:
opam: "open" failed on /Users/correnson/.opam/doc/lock: No such file or directory

When $HOME/.opam/doc exists:
$ opam doc <some pkg>
[ERROR] "/Users/correnson/.opam/doc" already exists, please choose a different name

**Comment by lpw25** [comment]
This seems to be a bug in opam. I've filed [an issue](https://github.com/ocaml/opam/issues/1813).
