### ISSUE TITLE
use something else than $("body")

### ISSUE THREAD

**Issue by pw374** [ocamllabs/opam-doc#11]
it's very non portable to use  $("body") rather than the id of a div section...

I might submit a pull request (since I had to modify that to make it work within the new ocaml.org design). However if you have any opinions on if it should be in a div or something else, or any thoughts about it etc, they are welcome.

**Comment by vincent-botbol** [comment]
I'd gladly accept any pull request on the Javascript part! I'm trying some other directions so I didn't really worked on improving the script.

**Comment by pw374** [comment]
The thing is, if I submit something for the javascript, I also have to submit something for the HTML... otherwise it'd be pointless.

**Comment by pw374** [comment]
I have a version where I replaced all `$("body")` by `$(ocontents)`, with 

```
ocontents = document.getElementById('main-contents');
```

I would not want to impose the use of `document.getElementById('main-contents')`. A tiny patch could be what I did with `ocontents = document.getElemenstByTagName('body')[0];` instead of `ocontents = document.getElementById('main-contents');`. Hmmm...

**Comment by pw374** [comment]
Well, I'll pull request in a few minutes!

edit: done!

**Comment by pw374** [comment]
fixed in 1fd1cab43fc716cac5095d601694c65aaa2f7958
closing
