### ISSUE TITLE
opamdoc loses some constructors

### ISSUE THREAD

**Issue by pw374** [ocamllabs/opam-doc#13]
I've just realised that on http://ocaml-redesign.github.io/docs/opam/?package=pcre-ocaml&module=Pcre the constructors of the type `error` that have no arguments are missing. It's not because of something I did to it. They are missing from the original html file that I got.

The `ml` file can be seen on https://bitbucket.org/mmottl/pcre-ocaml/src/2f6bad1617751a1a1f2701076920eaac9f685e5a/lib/pcre.ml?at=default
And the `mli` file is there: https://bitbucket.org/mmottl/pcre-ocaml/src/2f6bad1617751a1a1f2701076920eaac9f685e5a/lib/pcre.mli?at=default

I highly suspect a bug in opamdoc although I'm not yet 100% sure.

**Comment by amirmc** [comment]
I can see this elsewhere too. eg http://ocaml-redesign.github.io/docs/opam/?package=cstruct&module=Pa_cstruct

I noticed this on the output of opam-doc itself so it's a pre-existing issue.

**Comment by pw374** [comment]
Another example: http://ocaml-redesign.github.io/docs/opam/?package=cohttp&module=Accept_types&type=encoding

**Comment by pw374** [comment]
Ok I've found the bug. I'm making a pull request.

edit: done, now waiting...

**Comment by pw374** [comment]
it should be fixed  in 1fd1cab43fc716cac5095d601694c65aaa2f7958
closing...
