### ISSUE TITLE
Links not appearing for links to external modules

### ISSUE THREAD

**Issue by amirmc** [ocamllabs/opam-doc#20]
For example see the `Core.Std.*` lines in the following.

http://ocaml-redesign.github.io/docs/opam/?package=async_core&module=Async_or_error
edit: new url is  http://ocaml-redesign.github.io/pkg/docs/?package=async_core&module=Async_or_error

If you find any others, please add them here in the comments.

**Comment by pw374** [comment]
you mean there's no `[+]` button for `include Core.Std.Monad.S with type t := 'a t` ?

**Comment by lpw25** [comment]
That and the lack of links for types like `Core.Std.Or_error.t`. It looks like this file's documentation might have been generated before the `Core.Std` documentation had been generated.

**Comment by vincent-botbol** [comment]
You need to run the dependencies first. In this case, Core has to be processed before Async_core. Running opamdoc a second time will fix the problem.

**Comment by pw374** [comment]
Running opamdoc twice is not sufficient... or maybe I'm running it wrongly but then I'll need to know how to run it twice...

**Comment by vincent-botbol** [comment]
Works on my machine.. Can you post the building script?

**Comment by pw374** [comment]
that's what I'm running:

``` bash
#!/usr/bin/env bash
# Rebuild the cmd/cmt archive in ~/.opam/<switch>/opamdoc
# Copies all the cmt/cmti/cmd files found in the OPAM build
# dir into a single directory structure, separated by MD5
# to keep files distinct.

set -e
#dry=echo
SWITCH=$(opam switch show)
if [ "${SWITCH}" = "system" ]; then
  echo Must be using a custom OPAM switch for this to work.
  exit 1
fi

# OPAMDOC=${OPAMDOC:-opamdoc}
OPAMDOC=~/OCL/opam-doc/bin/opamdoc.opt

BASE="$(dirname $(dirname $(ocamlc -where)))"
BUILD=${BASE}/build
DOC=${BASE}/opamdoc
HTML=${BASE}/opamhtml

rm -rf ${HTML}
mkdir -p ${HTML}

# Grab the build dir in reverse mtime order to get the
# ordering of generation "correct".
PKGS=$(ls -1tr $BUILD)

rm -rf $HTML
mkdir -p $HTML
cd $HTML
for xxxx in 1 2 ; do
for pkg in ${PKGS}; do
  fs="$(find $DOC/$pkg -type f)"
  if [ "$fs" != "" ]; then
    name=$(echo $pkg | awk -F. '{print $1}')
    echo $pkg $name
    $dry $OPAMDOC -p $name $fs
  fi
done
done
```

**Comment by vincent-botbol** [comment]
Don't delete the previous build or keep the opam-doc.idx file then run it again.

The necessary hashtable for the package linking is stored there so if it's reset every time and you don't run core before async_core, it won't work.

**Comment by pw374** [comment]
I run opamdoc twice (cf. `for xxxx in 1 2 ; do ...`), and I don't see any deletion inside that loop, so I don't see what you mean :(

**Comment by vincent-botbol** [comment]
Ah sorry my bad, I didn't read quite well enough!

**Comment by pw374** [comment]
If you can generate the html files for all packages listed on http://ocaml.org.philippewang.info/pkg/docs/
then I'll gladly accept a PR on https://github.com/ocamllabs/sandbox-ocaml.org (cf. folder "opamhtml")

**Comment by pw374** [comment]
I think this has been fixed at some point. I'm closing this issue.
