### ISSUE TITLE
Cannot open Core_kernel.Std

### ISSUE THREAD

**Issue by amirmc** [ocamllabs/opam-doc#22]
Still hangs the browser.  I thought this was already fixed?

**Comment by amirmc** [comment]
Specifically, when I visit the following URL, my browser freezes.

http://ocaml-redesign.github.io/docs/opam/?package=core_kernel&module=Std_kernel

(don't try this at home, kids)

**Comment by pw374** [comment]
fixed by 4536859d56394333cffad3fc6b111a1ae33442f1
However don't visit http://ocaml-redesign.github.io/docs/opam/?package=core_kernel&module=Std_kernel before Friday 20 September 2013  **2am BST** unless you want to take risks. (Github can be very slow to update.)

**Comment by amirmc** [comment]
Reopening. This was _very_ slow to load in Safari, Chrome and Firefox (on MacOSX 10.8.4) and triggers the 'Unresponsive page/script' message in the latter two.  It did _eventually_ seem to load in Chrome (I gave up on Safari/Firefox)

**Comment by pw374** [comment]
Indeed, that's weird. Either it hasn't been updated correctly or something has wrongly changed.

**Comment by pw374** [comment]
@amirmc can you empty your browser's cache and try again please?

**Comment by lpw25** [comment]
I've fixed the includes, but I think that it is still loading all the content for the closed submodules. I'll fix those next.

**Comment by pw374** [comment]
Also I think we should try and rewrite the "big loop" in "CPS" so that the browser doesn't hang even when it has a lot to load.

**Comment by avsm** [comment]
That would be great...

**Comment by amirmc** [comment]
> @amirmc can you empty your browser's cache and try again please?

Reset history, cache, etc in Chrome and tried again.  I get the Unresponsive error after 20-ish seconds and the page still hasn't loaded.  (to be fair there may be GitHub issues at the moment - I was getting a 503 for a couple of minutes)

**Comment by amirmc** [comment]
Oh, now it's loaded (annoyed that I stopped my timer)

**Comment by pw374** [comment]
Now the script is using window.setTimeout at some places, this is enough for the browser to hang a little less: it gets reassured quite often that it's still the master of the universe. However, with big documents, it's still pretty much blocking the browser until it has finished loading. (So, yes, it's a small improvement, but no, it's not enough.)

**Comment by pw374** [comment]
@lpw25  fixed it with https://github.com/ocamllabs/opam-doc/pull/47 :)

see http://ocaml-redesign.github.io/pkg/docs/?package=core&module=Std
