### ISSUE TITLE
semi-colon in records are missing

### ISSUE THREAD

**Issue by pw374** [ocamllabs/opam-doc#28]
e.g., http://ocaml-redesign.github.io/docs/opam/?package=cow&module=Atom

**Comment by avsm** [comment]
There's also a lot of whitespace between the "type foo = {" and the next line.  This is because the </code></pre> shouldn't have any whitespace between them -- it's rendered directly.

-anil

**Comment by pw374** [comment]
I'm not sure it's because there's whitespace. It seems to me it's more because of the CSS and/or because there's a `table` following a `pre`.

Also, there are stuff like `<td align="left" valign="top"><code>  </code></td>`
in http://ocaml-redesign.github.io/docs/opam/cow/Atom.html

**Comment by pw374** [comment]
https://github.com/ocamllabs/sandbox-ocaml.org/commit/2684a15dc083c3cd6391a25e209b7b14e8f6f8a5 fixes some whitespace issues.

e.g., http://ocaml-redesign.github.io/docs/opam/?package=core_kernel&module=Core_list

**Comment by vincent-botbol** [comment]
Added the semi-colons in d767b336b6feaa265bf6d4f54828fb2d74d64da2

**Comment by pw374** [comment]
thanks :)
