### ISSUE TITLE
Core documentation being shoved to the bottom of the page

### ISSUE THREAD

**Issue by avsm** [ocamllabs/opam-doc#3]
According to @lpw25, this is due to camlp4:

> When I took camlp4 out of the equation (by running it separately and copying the 
> comments back into the output) these issues went away.
> If it is camlp4 related it will be incorrect handling of locations that
> is the cause.

So we should look at sexplib and binprot to check if they have location handling bugs that are causing this.  Note that this happens for vanilla ocamldoc too.

**Comment by amirmc** [comment]
Looks like this is now fixed.  For example see: http://ocaml-redesign.github.io/pkg/docs/?package=core_kernel&module=Core_list

Thanks to @lpw25 for the fix and @pw374 for regenerating the pages.  I'll let one of them close this off.
