### ISSUE TITLE
not yet in OPAM?

### ISSUE THREAD

**Issue by UnixJunkie** [ocamllabs/opam-doc#43]
:)

**Comment by pw374** [comment]
I believe it needs more work before it integrates "mainstream OPAM".

However you can already use OPAM to get it: https://github.com/ocamllabs/opam-doc/issues/1#issuecomment-23430108

I wrote some comments about this procedure if you want more details: http://pw374.github.io/posts/2013-09-24-01-50-14-opamdoc-take1.html

**Comment by lpw25** [comment]
I'm not sure opam-doc will ever be on OPAM in its current form. It will probably be changed into some libraries used by tools like opam2web. So I'm going to close this issue.
