### ISSUE TITLE
Using opam-doc with the system compiler is broken

### ISSUE THREAD

**Issue by samoht** [ocamllabs/opam-doc#68]
I've just cloned the repo and typed `make`. This gives me some errors while installing `ocamlfind`.

```
===== ERROR while installing ocamlfind.1.4.0 =====
# opam-version         1.1.1 (3305fa02cf8d135b0eff37d2418dcc20ff93bab5)
# os                   darwin
# command              ./configure -bindir /Users/thomas/git/opam-doc/opam/system/bin -sitelib /Users/thomas/git/opam-doc/opam/system/lib -mandir /Users/thomas/git/opam-doc/opam/system/man -config /Users/thomas/git/opam-doc/opam/system/lib/findlib.conf -no-topfind
# path                 /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0
# compiler             system (4.01.0)
# exit-code            1
# env-file             /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.env
# stdout-file          /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.out
# stderr-file          /Users/thomas/git/opam-doc/opam/system/build/ocamlfind.1.4.0/ocamlfind-99584-ffb3fd.err
### stdout ###
# Welcome to findlib version 1.4
# Configuring core...
### stderr ###
# configure: cannot determine ocaml's standard library directory
```

I guess this is because you've installed the `ocamlc` and `ocamlc.opt` which confuses ocamlfind configuration scripts when using the system compiler.

**Comment by avsm** [comment]
As a workaround, it does work inside a non-system switch.

**Comment by lpw25** [comment]
I'm afraid I don't fully understand this issue. How does ocamlfind usually find the standard library? Why does this not work when using a system compiler?

**Comment by samoht** [comment]
ocamlfind is calling `ocamlc -where` and if that fails, it uses a custom heuristic. I have a small patch to fix the return code of your scripts in that case (I'll create a PR), but this not seems to be enough. Didn't had enough time to dig deeper unfortunately.
